### ISSUE TITLE
Multiple UX360 Support

### ISSUE THREAD

**Issue by swamiller** [davidhewing/nexia_ux360#1]
I have 2 UX360 thermostats (upstairs and downstairs).  Only the downstairs device shows up with a configurable temperature, listed as "Zone 1", but will not work because the ID is duplicated with the upstairs unit.  There is not a way to change the default "Zone 1" ID for either unit. 
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:761
integration: Sensor (documentation, issues)
First occurred: 1:12:46 PM (3 occurrences)
Last logged: 1:12:46 PM

Platform nexia_ux360 does not generate unique IDs. ID 1_get_temperature already exists - ignoring sensor.zone_1_temperature
Platform nexia_ux360 does not generate unique IDs. ID 1_get_status already exists - ignoring sensor.zone_1_zone_status
Platform nexia_ux360 does not generate unique IDs. ID 1_get_setpoint_status already exists - ignoring sensor.zone_1_zone_setpoint_status
```

Also see this in the log after trying to adjust the temperature:
```
Logger:` homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:17:54 PM (3 occurrences)
Last logged: 2:21:31 PM

[139903573107632] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 1029, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/nexia_ux360-main/climate.py", line 345, in async_set_temperature
    await self._zone.set_heat_cool_temp(
  File "/config/custom_components/nexia_ux360-main/nexiaux360/zone.py", line 370, in set_heat_cool_temp
    await self._set_setpoints(cool_temperature, heat_temperature)
  File "/config/custom_components/nexia_ux360-main/nexiaux360/zone.py", line 402, in _set_setpoints
    await self._post_and_update_zone_json(
  File "/config/custom_components/nexia_ux360-main/nexiaux360/zone.py", line 552, in _post_and_update_zone_json
    response = await self._nexia_home.post_url(url, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nexia_ux360-main/nexiaux360/home.py", line 182, in post_url
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://asairhome.com/mobile/xxl_zones/1/setpoints'
```

**Comment by swamiller** [comment]
@davidhewing 
I don't believe this issue was induced by your code, I think it was a pre-existing issue.  I think it will require a different way of pulling the thermostat ID to account for multiple thermostats (with a default "zone 1" ID).  I don't have any experience as a developer, but is there anything I can do to help with a solution?

**Comment by davidhewing** [comment]
@swamiller Yeah, I understand the multiple thermostat problem.  The original code gets the zone name from the Trane API, but Trane doesn't provide a way to actually name a zone.  The solution is exactly as you say, to create a zone entities with the thermostat id as part of the name, but I haven't jumped into the code to figure out how exactly to do that.  I'll try to take a look the next time I get some free time.  

In my setup, I have noticed that sometimes the API does not return an expected value for the original code when adjusting the temperature, but it does update and the HA values will update during the next check against the Trane cloud service.

I was really hoping the original developer would have been interested in taking this on since I do not have near the skill level they do.

**Comment by davidhewing** [comment]
@swamiller This repo should now support mutliple thermostats.  I managed to add thermostat information to the zone entry names that should allow them to be unique.  I suspect you will have to delete your existing thermostat setup and the follow all the setup directions again.

**Comment by swamiller** [comment]
Thank you!!  I very much appreciate you working on this! 
I installed the update and we're closer.  I can see both my upstairs and downstairs but only the downstairs has the built in Home Assistant thermostat "Controls" functionality.  

Downstairs:
![image](https://github.com/user-attachments/assets/ef8a314a-cdfc-4f40-8d22-2829bc901b3b)

Upstairs:
![image](https://github.com/user-attachments/assets/bde3db0d-681c-4e8b-b2a6-862bdf170283)


For the downstairs thermostat view, it will properly show what the temp the thermostat is set but trying to send a change from Home Assistant gives a 404 error message.  
```
Failed to perform the action climate/set_temperature. 404, message='Not Found', url='https://asairhome.com/mobile/xxl_zones/1/setpoints' 
```
Here is what is in the log file:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:02:02 PM (7 occurrences)
Last logged: 7:04:15 PM

[139918871519312] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 1029, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/nexia_ux360/climate.py", line 345, in async_set_temperature
    await self._zone.set_heat_cool_temp(
  File "/config/custom_components/nexia_ux360/nexiaux360/zone.py", line 383, in set_heat_cool_temp
    await self._set_setpoints(cool_temperature, heat_temperature)
  File "/config/custom_components/nexia_ux360/nexiaux360/zone.py", line 415, in _set_setpoints
    await self._post_and_update_zone_json(
  File "/config/custom_components/nexia_ux360/nexiaux360/zone.py", line 565, in _post_and_update_zone_json
    response = await self._nexia_home.post_url(url, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nexia_ux360/nexiaux360/home.py", line 182, in post_url
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://asairhome.com/mobile/xxl_zones/1/setpoints' ```


Please let me know what other information I can provide.  I think you're really close to a solution.

**Comment by davidhewing** [comment]
@swamiller I have updated this again was a new diagnostics directory that includes a dump_json.py script that can be run from the ssh command line.  There is a read.me file that details how to get that working.  The JSON output will barely be human readable, but will contain important information about your particular setup that might give some clues.  Please look through that output first and scrub out any personally identifiable information (name, location, email, etc), and send it back my way.

**Comment by swamiller** [comment]
Ok, secondary issue just popped up.  I deleted the install, installed the latest build via GIT, rebooted (twice) but I am getting this error when I click on the integration to set it up:
```
Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 9:00:45 AM (1 occurrences)
Last logged: 9:00:45 AM

Error occurred loading flow for integration nexia_ux360: No module named 'custom_components.nexia_ux360.nexiaux360.thermostat'
```
Missing file?

Here is a snapshot of my installed file structure:
![image](https://github.com/user-attachments/assets/ab4c27d6-999d-4eef-950f-68fa3122bd68)

**Comment by davidhewing** [comment]
Should be fixed again.  I accidentally moved files around and didn't copy them and then proceeded not to test the changes in my test environment.  Basically skipping all the steps of a real developer.  :-)

**Comment by swamiller** [comment]
Got it loaded and set up!  Not sure what other changes you made, but I can now control my downstairs thermostat (no 404 error).  Upstairs is still missing the "Controls" card but properly reflecting the data for the upstairs thermostat, just no way to adjust the temperature.  At this point, the missing control for the second upstairs thermostat seems to be the only remaining issue.  Do you still need me to run the diagnostic script to troubleshoot that issue?

Couple of issues I noticed in the log:
```
Logger: homeassistant.config_entries
Source: config_entries.py:1645
First occurred: 6:21:52 PM (2 occurrences)
Last logged: 6:21:52 PM

Config entry 'Foxglove Manor' from integration nexia_ux360 has an invalid unique_id '2496162' of type int when a string is expected, please report it to the author of the 'nexia_ux360' custom integration
```
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:764
integration: Climate (documentation, issues)
First occurred: 6:21:53 PM (1 occurrences)
Last logged: 6:21:53 PM

Platform nexia_ux360 does not generate unique IDs. ID 1 already exists - ignoring climate.downstairs_zone_1
```
```
Logger: homeassistant.helpers.entity_registry
Source: helpers/entity_registry.py:667
First occurred: 6:21:53 PM (5 occurrences)
Last logged: 6:21:54 PM

'climate' from integration nexia_ux360 has a non string unique_id '1', please report it to the author of the 'nexia_ux360' custom integration
'scene' from integration nexia_ux360 has a non string unique_id '5037713', please report it to the author of the 'nexia_ux360' custom integration
'scene' from integration nexia_ux360 has a non string unique_id '5037702', please report it to the author of the 'nexia_ux360' custom integration
'scene' from integration nexia_ux360 has a non string unique_id '5037710', please report it to the author of the 'nexia_ux360' custom integration
'switch' from integration nexia_ux360 has a non string unique_id '1', please report it to the author of the 'nexia_ux360' custom integration
```
```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:764
integration: Switch (documentation, issues)
First occurred: 6:21:54 PM (1 occurrences)
Last logged: 6:21:54 PM

Platform nexia_ux360 does not generate unique IDs. ID 1 already exists - ignoring switch.downstairs_zone_1_hold
```

**Comment by davidhewing** [comment]
@swamiller  Probably to make any more progress I would need the json output from that diagnostic program following the steps that I indicated previously,  I'm not sure about the non strng unique_id messages.  I think I see those too in my copy but it doesn't seem to impact functionality.

**Comment by swamiller** [comment]
[ux360datadump.json](https://github.com/user-attachments/files/17961303/ux360datadump.json)

Here is the unedited data.  I didn't see my name or email address anywhere, although I did leave my house ID and thermostat IDs in place.  If that was a mistake, let me know.

**Comment by davidhewing** [comment]
@swamiller as far as I can tell there aren't any problems with how the code is setting things up now.  I'd recommend trying to delete the integration and all the entities, restart home assistant, and then add the integration back.  It should create all the correct entities from that point.  If you don't get a card for both your upstairs and your downstairs, just try creating the missing climate card.  If that doesn't work, it might be helpful to see the list of entities that show up in your system:

![image](https://github.com/user-attachments/assets/9fddb8d0-6433-438f-bf03-f523b3fcab5b)

**Comment by swamiller** [comment]
I deleted the integration and deleted the custom component file/folder.  I also manually deleted any entities associated with Nexia integration.  I restarted, re-downloaded from GIT, restarted, setup the integration...same result, no control for upstairs unit.  I tried to set up a thermostat card manually, but Home Assistant will not let you select a "non-thermostat" (climate entity) type entity for this card.  Here were my choices for creating a thermostat card:
![image](https://github.com/user-attachments/assets/2e8dc67b-96e8-4f9e-9be1-f873c2df9e1e)
First choice being the downstairs ux360 and the other being my truck.

Looks like the integration is only applying the climate entity type to the first thermostat.

**Comment by davidhewing** [comment]
Can you show me a list of all your entities from the Nexia integration page?

**Comment by swamiller** [comment]
Sure, there are 25 total entities between both thermostats.

Here is the list in its entirety:
``` 
Downstairs Night
scene.downstairs_night
Nexia/American Standard/Trane UX360
—
—
Weekday Downstairs Temp
scene.weekday_downstairs_temp
Nexia/American Standard/Trane UX360
—
—
Weekday Upstairs Temp Unoccupied
scene.weekday_upstairs_temp_unoccupied
Nexia/American Standard/Trane UX360
—
—
Downstairs_Zone 1
climate.downstairs_zone_1
Nexia/American Standard/Trane UX360
—
Downstairs Blower active
binary_sensor.downstairs_blower_active
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs System status
sensor.downstairs_system_status
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs Air cleaner mode
sensor.downstairs_air_cleaner_mode
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs Current compressor speed
sensor.downstairs_current_compressor_speed
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs Requested compressor speed
sensor.downstairs_requested_compressor_speed
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs Outdoor temperature
sensor.downstairs_outdoor_temperature
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs Humidity
sensor.downstairs_humidity
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs_Zone 1 Temperature
sensor.downstairs_zone_1_temperature
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs_Zone 1 Zone status
sensor.downstairs_zone_1_zone_status
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs_Zone 1 Zone setpoint status
sensor.downstairs_zone_1_zone_setpoint_status
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs_Zone 1 Hold
switch.downstairs_zone_1_hold
Nexia/American Standard/Trane UX360
Downstairs
—
Downstairs_Zone 1
climate.downstairs_zone_1
Nexia/American Standard/Trane UX360
Downstairs
—
Upstairs Blower active
binary_sensor.upstairs_blower_active
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs System status
sensor.upstairs_system_status
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs Air cleaner mode
sensor.upstairs_air_cleaner_mode
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs Current compressor speed
sensor.upstairs_current_compressor_speed
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs Requested compressor speed
sensor.upstairs_requested_compressor_speed
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs Outdoor temperature
sensor.upstairs_outdoor_temperature
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs Humidity
sensor.upstairs_humidity
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs_Zone 1 Temperature
sensor.upstairs_zone_1_temperature
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs_Zone 1 Zone status
sensor.upstairs_zone_1_zone_status
Nexia/American Standard/Trane UX360
Upstairs
—
Upstairs_Zone 1 Zone setpoint status
sensor.upstairs_zone_1_zone_setpoint_status
Nexia/American Standard/Trane UX360
Upstairs
—
```

**Comment by davidhewing** [comment]
@swamiller Ok, I have done a bunch of new changes.  I've tried to make the zones id information unque.  This might make it finally provide two climate devices

I also  move everything that has an id to a string instead of a numeric value.  I continue to see the same errors in the logs though about the "str" expected messages. Not sure how to really fix that.

So as always, delete your current entities, delete the nexia_ux360 directory, and get a new copy, restart HA, and create your device again.

**Comment by swamiller** [comment]
@davidhewing I really appreciate you working on this!  

Unfortunately, no change - still no climate control entity for the upstairs thermostat.  I do see this error in the log which might be a clue:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:764
integration: Climate (documentation, issues)
First occurred: 1:09:24 PM (1 occurrences)
Last logged: 1:09:24 PM

Platform nexia_ux360 does not generate unique IDs. ID 1 already exists - ignoring climate.downstairs_zone_1
```
Since the downstairs thermostat is setting up first (and correctly), it looks like the climate.downstairs_zone_1 should actually be climate.upstairs_zone_1?  I have a similar error for the "hold" switch which is also a part of the climate controls card:

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:764
integration: Switch (documentation, issues)
First occurred: 1:09:25 PM (1 occurrences)
Last logged: 1:09:25 PM

Platform nexia_ux360 does not generate unique IDs. ID 1 already exists - ignoring switch.downstairs_zone_1_hold
```
On another note, I noted that "Auto" under the "Mode" drop down for the downstairs control throws a 404 error.   The "Heat/Cool" option and separate Heat, Cool, and Off all work and sets the respective setting on the physical thermostat.  "Presets" selections also give 404 errors.

**Comment by davidhewing** [comment]
@swamiller  Think we're getting closer.  Yet another update for you to test.    In my test instance, I'm no longer getting errors about IDs already existing.  Maybe this is the one.

**Comment by swamiller** [comment]
You are a rockstar!!  Both thermostats are now controllable!

Only 2 errors in the log"
```
Logger: homeassistant.config_entries
Source: config_entries.py:1645
First occurred: 5:18:27 PM (2 occurrences)
Last logged: 5:18:27 PM

Config entry 'Foxglove Manor' from integration nexia_ux360 has an invalid unique_id '2496162' of type int when a string is expected, please report it to the author of the 'nexia_ux360' custom integration
```

```
Logger: homeassistant.helpers.entity_registry
Source: helpers/entity_registry.py:667
First occurred: 5:18:28 PM (3 occurrences)
Last logged: 5:18:28 PM

'scene' from integration nexia_ux360 has a non string unique_id '5037713', please report it to the author of the 'nexia_ux360' custom integration
'scene' from integration nexia_ux360 has a non string unique_id '5037702', please report it to the author of the 'nexia_ux360' custom integration
'scene' from integration nexia_ux360 has a non string unique_id '5037710', please report it to the author of the 'nexia_ux360' custom integration
```
Mode select was acting odd, selected "Heat" and it went back to "Auto" in the selection but sent the right command to the thermostat.   Otherwise, looks pretty good!

**Comment by davidhewing** [comment]
Awesome!  I still haven't found the source for the non string unique_id messages are coming from.  

The only of thing that worth mentioning is that  some changes you make within home assistant make take to to 2 minutes to actually be reflected as the current status of an entity.   This is due to this being a polled cloud service.   The actual change should happen on the thermostat(s) themselves very quickly as long as there is no problem with the cloud.  I really wish there was the ability to locally control these thermostats, but I'm not prepared to try to dive into the signaling used to the thermostat itself.

Suppose I will close this issue since it now seems to work with multiple ux360s.

**Comment by swamiller** [comment]
Agree, thank you for getting this integration working!
